export const hobbyTags = [
  "Sports",
  "Outdoor Activities",
  "Fitness",
  "Travel",
  "Reading",
  "Writing",
  "Music",
  "Singing",
  "Dancing",
  "Playing Instruments",
  "Art",
  "Drawing",
  "Painting",
  "Photography",
  "Crafts",
  "DIY Projects",
  "Cooking",
  "Baking",
  "Gardening",
  "Home Improvement",
  "Technology",
  "Programming",
  "Gaming",
  "Board Games",
  "Puzzles",
  "Collecting",
  "Volunteering",
  "Community Service",
  "Learning Languages",
  "Meditation",
  "Yoga",
  "Mindfulness",
  "Spirituality",
  "Philosophy",
  "History",
  "Science",
  "Nature",
  "Pet Care",
  "Animal Training",
  "Theater",
  "Acting",
  "Filmmaking",
  "Fashion",
  "Beauty",
  "Skincare",
  "Makeup",
  "Woodworking",
  "Metalworking",
  "Electronics",
  "Robotics",
  "Knitting",
  "Crocheting",
  "Sewing",
  "Embroidery",
  "Jewelry Making",
  "Blogging",
  "Vlogging",
  "Social Media",
  "Podcasting",
  "Public Speaking",
  "Debate",
  "Politics",
  "Activism",
  "Environmentalism",
  "Sustainability",
  "Personal Development",
  "Leadership",
  "Entrepreneurship",
  "Investing",
  "Personal Finance",
  "Astronomy",
  "Birdwatching",
  "Hiking",
  "Camping",
  "Fishing",
  "Hunting",
  "Surfing",
  "Skateboarding",
  "Snowboarding",
  "Skiing",
  "Climbing",
  "Martial Arts",
  "Archery",
  "Fencing",
  "Shooting Sports",
  "Scuba Diving",
  "Snorkeling",
  "Sailing",
  "Boating",
  "Flying",
  "Skydiving",
  "Paragliding",
  "Hang Gliding",
  "Geocaching",
  "Orienteering",
  "Survival Skills",
  "Prepping",
  "Homesteading",
  "Farming",
  "Beekeeping",
  "Winemaking",
  "Brewing",
  "Distilling",
  "Mixology",
  "Coffee Roasting",
  "Tea Tasting",
  "Chocolate Making",
  "Cheese Making",
  "Foraging",
  "Mushroom Hunting",
  "Herbalism",
];
